---
title: "BMI Calculation using Shiny"
author: "Kirty Vedula"
date: "04/26/2015"
output:
  ioslides_presentation:
    keep_md: yes
    widescreen: yes
runtime: shiny
---

## Presentation Outline

This presentation is created to introduce a web-based application called "BMI Calc". The presentation proides information about this application by focusing on the following topics

- What is BMI Calc?
- How does BMI Calc Work?
- Why use BMI Calc?

## What is BMI Calc?

- BMI Calc is a web-based application that allows the user to find out what their Body Mass Index is
- Body Mass Index (BMI) is a measure of relative mass based on ones height and weight
- BMI is an important indicator of one's risk for many chronic conditions that are especially prevalent among older people
- The index measures body mass on a continuous surface
- The index has also been used to classify body mass into clinically meaningful categories


## How does BMI Calc work?

- The BMI calculator (BMI Calc) asks for the following inputs from the user:
-- The respondent's weight
-- The respondent's height
- Note that the unit of measurement units that the application expects by way of input is the "imperial" units
- This means that if you know your measurements only in terms of metric units, you must make the transformation before entering them into the application
- Failing to use the appropriate unit of measurement will result in erronous results


## Slide with R Code and Output

```{r}
BMI<-function(weight,height) {weight/(height^2)}

diagnostic_f<-function(weight,height){
  BMI_value<-weight/(height^2)
  ifelse(BMI_value<18.5,"underweight",ifelse(BMI_value<25,"normal weight",ifelse(BMI_value<30,"overweight","obesity")))
}
```


